<?php
return [
  'site' => [
    'site_name' => 'swiftadmin',
    'site_url' => 'www.swiftadmin.net',
    'site_logo' => '/static/images/logo.png',
    'site_http' => 'http://www.swiftadmin.net',
    'site_path' => '/',
    'site_icp' => '京ICP备13000001号',
    'site_email' => 'admin@swiftadmin.net',
    'site_keyword' => '网站关键字',
    'site_description' => '网站描述',
    'site_total' => '统计代码：',
    'site_copyright' => '版权信息：',
    'site_status' => '1',
    'site_notice' => 'html',
  ],
  'file' => '',
  'auth' => [
    'auth_code' => 'FDX8SAWA9',
    'auth_key' => 'MATwC7mt',
  ],
  'sphinx' => [
    'sphinx_status' => '0',
    'sphinx_host' => 'localhost',
    'sphinx_port' => '9213',
  ],
  'logs' => [
    'admin_log_status' => '0',
    'system_log_status' => '0',
  ],
  'cache' => [
    'cache_status' => '1',
    'cache_type' => 'redis',
    'cache_time' => '600',
    'cache_host' => '127.0.0.1',
    'cache_port' => '6379',
    'cache_user' => '',
    'cache_pass' => '',
  ],
  'upload' => [
    'upload_path' => 'upload',
    'upload_style' => 'Y-m-d',
    'upload_class' => [
      'images' => '.bmp.jpg.jpeg.png.gif',
      'video' => '.flv.swf.mkv.avi.rm.rmvb.mpeg.mpg.ogg.ogv.mov.wmv.mp4.webm.mp3.wav.mid',
      'document' => '.txt.doc.xls.ppt.docx.xlsx.pptx',
      'files' => '.exe.dll.sys.so.dmg.iso.zip.rar.7z.sql.pem',
    ],
    'upload_ftp' => '0',
    'upload_del' => '0',
    'upload_ftp_host' => '127.0.0.1',
    'upload_ftp_port' => '26655',
    'upload_ftp_user' => '123123',
    'upload_ftp_pass' => '5BGMMATwC7mtGp4m',
    'upload_http_prefix' => 'http://****.com',
    'upload_thumb' => '0',
    'upload_thumb_w' => '120',
    'upload_thumb_h' => '140',
    'upload_water' => '1',
    'upload_water_type' => '1',
    'upload_water_font' => 'swiftAdmin.net',
    'upload_water_size' => '20',
    'upload_water_color' => '#0fbeea',
    'upload_water_pct' => '49',
    'upload_water_img' => '/upload/images/2020-12-22/5fe1f8e43657e.png',
    'upload_water_pos' => '9',
  ],
  'cloud' => [
    'status' => '0',
    'type' => 'qcloud',
    'aliyun' => [
      'accessId' => 'Iq8qZla2z5BKTW1N',
      'accessSecret' => 'nCr3f5aCYo7aLdBrFFLCprYGNngTZ8',
      'bucket' => 'jijutv',
      'endpoint' => 'oss-cn-beijing.aliyuncs.com',
      'url' => 'http://oss-cn-beijing.aliyuncs.com',
    ],
    'qcloud' => [
      'app_id' => '1252296528',
      'secret_id' => 'AKIDzZtymNEdKqyueM90veVM2SMfleIlRiog',
      'secret_key' => 'kFStrmkXjHjw97ankaJdoIXXSScjRt9A',
      'bucket' => 'testpack',
      'region' => 'ap-beijing',
      'url' => '',
    ],
  ],
  'email' => [
    'smtp_debug' => '0',
    'smtp_host' => 'smtp.163.com',
    'smtp_port' => '587',
    'smtp_name' => '管理员',
    'smtp_user' => 'yourname@163.com',
    'smtp_pass' => 'password',
    'smtp_test' => '',
  ],
  'social' => [
    'qq' => [
      'app_id' => '',
      'app_key' => '',
      'callback' => '',
    ],
    'weixin' => [
      'app_id' => '',
      'app_key' => '',
      'callback' => '',
    ],
    'weibo' => [
      'app_id' => '',
      'app_key' => '',
      'callback' => '',
    ],
  ],
  'payface' => [
    'alipay' => [
      'app_id' => '2021000117628417',
      'ali_public_key' => 'MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAlmgwiCuMXJ/gFNU3tMOubHOANoOiRNrdZMiDgzohtD/3T2k71vMV6SNiqxut/Rvv1Cn4phneeycVfrh7XYCL/FiNeFdUPr++5k0nvwkVqdHHRGDvKbDem7jHsBi5Zk49Lv++EI7Fn/p25cwBpj8WbjoHrbWkec2unKv9u9CBjscejQvZ3P2seDZo33VB1gnabYM0HHmlXYRx2dLSNOMz+++WUcXmb6s/f1yAf94lHpLgnHjziXZDk/mETD9SOsp6Ca+9CFUdhku2NLlc9CwF8fCh+kkLa+tYqwEpY1/+Kbq4gO2/Bwn5m2yyH6D3kwW0ORyW7fh1rG0mH5zI0CqCZQIDAQAB',
      'private_key' => 'MIIEogIBAAKCAQEAicgMM+/G05Kd0IVQhIyCMWUOIgXoLWQULXwDy/SSWzWSeGgEedg61YoKRd4j1DLL9Hhbxp0+v4yHfFjVghPzOUfV8zFJwuLE74flvYnQWz17IuBbjswGoZj3dn9ThqBi4dQPr2LnufNTSJyt5rvOsBDSL17ns8KpUfQk4LUaPGKPVWHCSSii85DaTEk6vWqHRMk+qZbOryjtlinOIji+ruy4fJtOCqrMHBlZGjMwdVVBPwkB5eHIUZrRHlpHhYvcNnHeLVYBv+1ejpqtG9s0IxmHaDxkZqZro2tfgnQ+M1fgmisx/IpQvQSsLG6L4hcI4DrBf8g9akpGTEadnFFbzwIDAQABAoIBAHWF8oq2grTjAcPkgxqcs0yosxZoTXOyQtfNSXvF4LT2DDqyFudLflu4xCx2X79XmMqtgzL125kNqF9zcqLim3uHf8JRj2YxgeQC2f8DN3ssBQVptA8ojpt2W9Zyou9ZjR6tgLeMOLZPDAIKyvbdyV466t3HKQIXD9A83Nvi/j70WfgNkVULq32K2ZXkNsOo2jYfd+dds2JQPOrWG1DComvGD2LCk7CWGWGHgUVtGeRLwCHiS7NckPkXIwDOYeNGLEXG0Hzt99LSbCa8BKL4PY43pBLlxj8DZ8MIYe/buoXzGZqgVcl3KS76738QJwh8HidpmeNcYu/ECC1O/ME8SEkCgYEA3jd+dVrLHZnXRDf0dyWlRPNYEzg4aWKrWmlN7+jjCljb4tyH9Ib6384NKm9QD41OgeOD0pdI8EjC3sy2yv+QYpnSWr0bRv1952rTMhH/R2xqEMOmdp22W7VLfZ8K12wcAYYHF4OLQLJ8dTIjBh1CvpdCFBR8LEt//CHYRamQidUCgYEAnrplMBPKB8BgxTaLsBbYTk60eY+mfgc1aOILBdGzS5wZJUTE6gG+gSHITQjgLFzNIWp78yW6Z9soXypRKpHcgE/XpxF6GiSPTDvFRFq+Qru5/+XgazI30LQIWSy3u4TtvNM40ujJj8p5IKu9TOW8rgd8Pb9ilm32DnX/PB4SHRMCgYAzlTQwr7PImkaDGm4QHlf/6nD+fSVzKSlXomwqDahuZXQddE3G8HJZ823Q9OfjxEx+ED8walfPF0TNDT49Xxe4G7bdw1oKn5tTVdPSoqTcgokYfSIuFKwZG7t7XKjamsjhfag1yB5SFVyYo9vHdpFgxqHbIWo1qgz6jSyz9wmLRQKBgGIhcI+BnISgTfN+3mt2JDJ9fBwvUEpYIJAAN7pYQ9W54t3knyzg+SsSfKgLlbQ3h2ZiU9EmARFWL6ZuHhIIbV8yfWu/ZVKmSaViynmQ9FGDh+GJ9+2t9U3lD8g52jlnXCdCGr5hxsNL9QjaxES3P6gD3q66FLRVtSqJjstW9/HbAoGAf0y71TQx90Lx4jqbuzG4L5zEE6qtmFhhYWTi0D9c+PBrqXLjrZtEk/f+GTHbjttR0uw3CuKAWg/hzk3ouqzMGaGxIbMzNn+XiE2GfjLk13NuEa565oFYs9LGSsfax+2hnvgwvFfdj4d405jdu9/WVGUNmiSvBMEYhsHsapFKIN4=',
      'return_url' => 'http://www.swiftadmin.net/order/pay',
      'notify_url' => 'http://www.swiftadmin.net/order/pay',
      'cert_client' => '',
      'cert_key' => '',
      'mode' => 'dev',
    ],
    'wechat' => [
      'app_id' => '',
      'mch_id' => '',
      'appid' => '',
      'key' => '',
      'miniapp_id' => '',
      'notify_url' => '',
      'cert_client' => '',
      'cert_key' => '',
      'mode' => '',
    ],
  ],
  'smsface' => [
    'type' => 'alisms',
    'alisms' => [
      'app_id' => 'cn-hangzhou',
      'app_sign' => '河北赢图网络科技有限公司',
      'access_id' => 'Iq8qZla2z5BKTW1N',
      'access_secret' => 'nCr3f5aCYo7aLdBrFFLCprYGNngTZ8',
    ],
    'tensms' => [
      'app_id' => '1400459798',
      'app_sign' => '邯郸市城企建材有限公司',
      'secret_id' => 'AKIDzZtymNEdKqyueM90veVM2SMfleIlRiog',
      'secret_key' => 'kFStrmkXjHjw97ankaJdoIXXSScjRt9A',
    ],
  ],
  'wechat' => [
    'secret_id' => '2121',
    'secret_key' => '1212',
  ],
  'user' => [
    'user_status' => '1',
    'user_register_style' => 'normal',
    'user_document' => '1',
    'user_document_integra' => '1',
    'user_valitime' => '10',
    'user_register_second' => '10',
    'user_login_integra' => '1',
    'user_spread_integra' => '1',
    'user_search_interval' => '1',
    'user_reg_notallow' => 'www,bbs,ftp,mail,user,users,admin,administrator',
    'user_form_status' => '1',
    'user_form_check' => '0',
    'user_isLogin' => '0',
    'user_anonymous' => '0',
    'user_form_second' => '10',
    'user_replace' => '她妈|它妈|他妈|你妈|去死|贱人',
  ],
  'sitemap' => [
    'status' => '1',
    'index_freq' => 'always',
    'list_freq' => 'hourly',
    'content_freq' => 'daily',
    'index_priority' => '1.0',
    'list_priority' => '0.8',
    'content_priority' => '0.6',
    'map_xml_max' => '10000',
    'map_xml_path' => 'swiftmaps',
    'map_xml_token' => 'baidutoken',
  ],
  'rewrite' => [
    'URL_MODEL' => '1',
    'list_page' => '{listdir}/list_{page}.html',
    'content_page' => '{listdir}/{id}/',
    'list_type' => 'lists-id-{id}',
  ],
  'database' => [
    'path' => 'static\\_backup',
    'part' => '20971',
    'compress' => '1',
    'level' => '9',
  ],
  'plugin' => [
    'mutex_file' => '1',
  ],
  'variable' => [
    'test' => '我是值2',
    'ceshi' => '我是测试变量的值',
  ],
];