<?php
return [
  'site' => [
    'site_name' => '基于ThinkPHP和layui的极速后台开发框架',
    'site_url' => 'www.swiftadmin.net',
    'site_logo' => '/static/images/logo.png',
    'site_http' => 'http://www.swiftadmin.net',
    'site_path' => '/',
    'site_icp' => '京ICP备13000001号',
    'site_email' => 'admin@swiftadmin.net',
    'site_keyword' => '网站关键字',
    'site_description' => '网站描述',
    'site_total' => '统计代码：',
    'site_copyright' => '版权信息：',
    'site_notlink' => '1',
    'site_status' => '0',
    'site_notice' => 'html',
  ],
  'file' => '',
  'auth' => [
    'auth_code' => '38nfCIlkqNMI2',
    'auth_key' => 'WS3hi5Xe0Wx7rXkx',
  ],
  'fulltext' => [
    'search_status' => '0',
    'search_model' => 'XunSearch',
  ],
  'logs' => [
    'admin_log_status' => '0',
    'system_log_status' => '0',
  ],
  'cache' => [
    'cache_status' => '1',
    'cache_type' => 'redis',
    'cache_time' => '6000',
    'cache_host' => '127.0.0.1',
    'cache_port' => '6379',
    'cache_select' => '1',
    'cache_user' => '',
    'cache_pass' => '',
  ],
  'upload' => [
    'upload_path' => 'upload',
    'upload_style' => 'Y-m-d',
    'upload_class' => [
      'images' => '.bmp.jpg.jpeg.png.gif.svg',
      'video' => '.flv.swf.mkv.avi.rm.rmvb.mpeg.mpg.ogg.ogv.mov.wmv.mp4.webm.mp3.wav.mid',
      'document' => '.txt.doc.xls.ppt.docx.xlsx.pptx',
      'files' => '.exe.dll.sys.so.dmg.iso.zip.rar.7z.sql.pem',
    ],
    'upload_ftp' => '0',
    'upload_del' => '1',
    'upload_ftp_host' => '127.0.0.1',
    'upload_ftp_port' => '26655',
    'upload_ftp_user' => '123123',
    'upload_ftp_pass' => '5BGMMATwC7mtGp4m',
    'upload_http_prefix' => 'https://img.swiftadmin.net',
    'upload_http_auto' => '1',
    'upload_thumb' => '0',
    'upload_thumb_w' => '120',
    'upload_thumb_h' => '140',
    'upload_water' => '1',
    'upload_water_type' => '1',
    'upload_water_font' => 'www.swiftadmin.net',
    'upload_water_size' => '20',
    'upload_water_color' => '#0fbeea',
    'upload_water_pct' => '49',
    'upload_water_img' => '/',
    'upload_water_pos' => '9',
  ],
  'play' => [
    'play_width' => '960',
    'play_height' => '450',
    'play_show' => '0',
    'play_second' => '10',
    'play_area' => '大陆,香港,中国台湾,美国,韩国,日本,泰国,印度,英国,法国,俄罗斯,新加坡,其它',
    'play_year' => '2021,2020,2019,2018,2017,2016,2015,2014,2013,2012,2011,2010,2009,2008,2007,2006,2005,2004,2003,2002,2001,2000,1999',
    'play_version' => '高清版,剧场版,抢先版,OVA,TV,影院版',
    'play_language' => '国语,英语,粤语,韩语,日语,法语,德语,泰语,俄语,其它',
    'play_week' => '周一,周二,周三,周四,周五,周六,周日',
    'play_playad' => 'http://www.swiftadmin.net/api/show.html',
    'play_down' => 'http://www.swiftadmin.net/api/show.html',
    'play_downgorup' => 'http://down.swiftadmin.net/',
  ],
  'cloud' => [
    'status' => '0',
    'type' => 'aliyun',
    'aliyun' => [
      'accessId' => 'LTAI5333kuER9w3xNnVMe1vC',
      'accessSecret' => 'kFStrmkXjHjw9sankaJdocxsSScjRt9A',
      'bucket' => 'demo',
      'endpoint' => 'oss-cn-beijing.aliyuncs.com',
      'url' => 'http://oss-cn-beijing.aliyuncs.com',
    ],
    'qcloud' => [
      'app_id' => '1252296528',
      'secret_id' => 'LTAI5333kuER9w3xNnVMe1vC',
      'secret_key' => 'kFStrmkXjHjw9sankaJdocxsSScjRt9A',
      'bucket' => 'testpack',
      'region' => 'ap-beijing',
      'url' => '',
    ],
  ],
  'email' => [
    'smtp_debug' => '0',
    'smtp_host' => 'smtp.163.com',
    'smtp_port' => '587',
    'smtp_name' => '管理员',
    'smtp_user' => 'yourname@163.com',
    'smtp_pass' => 'password',
    'smtp_test' => '',
  ],
  'social' => [
    'qq' => [
      'app_id' => '',
      'app_key' => '',
      'callback' => '',
    ],
    'weixin' => [
      'app_id' => '',
      'app_key' => '',
      'callback' => '',
    ],
    'gitee' => [
      'app_id' => '',
      'app_key' => '',
      'callback' => '',
    ],
    'weibo' => [
      'app_id' => '',
      'app_key' => '',
      'callback' => '',
    ],
  ],
  'payface' => [
    'alipay' => [
      'mode' => '0',
      'app_id' => '202100213462****',
      'app_public_cert_path' => 'appCertPublicKey_20210021346*****.crt',
      'app_secret_cert' => '7eUBvZLxn8XwZPuCA==',
      'return_url' => 'https://www.swiftadmin.net/',
      'notify_url' => 'https://www.swiftadmin.net/',
      'alipay_public_cert_path' => 'alipayCertPublicKey_RSA2.crt',
      'alipay_root_cert_path' => 'alipayRootCert.crt',
    ],
    'wechat' => [
      'mode' => '0',
      'mch_id' => '16138*****',
      'mch_secret_key' => 'GgnohjtLdR******rprA6duxQ8k0AuVA',
      'mp_app_id' => 'wxd2bf0834be*****',
      'mini_app_id' => '',
      'notify_url' => 'https://www.swiftadmin.net/',
      'mch_secret_cert' => 'apiclient_key.pem',
      'mch_public_cert_path' => 'apiclient_cert.pem',
    ],
  ],
  'smsface' => [
    'type' => 'alisms',
    'alisms' => [
      'app_id' => 'cn-hangzhou',
      'app_sign' => '河北邯郸市有限公司',
      'access_id' => 'kFStrmkXjHjw9sankaJdoIXXSScjRt9A',
      'access_secret' => 'kFStrmkXjHjw9sankaJdoIXXSScjRt9A',
    ],
    'tensms' => [
      'app_id' => '1400459798',
      'app_sign' => '河北邯郸市有限公司',
      'secret_id' => 'kFStrmkXjHjw9sankaJdoIXXSScjRt9A',
      'secret_key' => 'kFStrmkXjHjw9sankaJdoIXXSScjRt9A',
    ],
  ],
  'mpwechat' => [
    'secret_id' => '',
    'secret_key' => '',
    'secret_token' => '',
    'EncodingAESKey' => '',
  ],
  'user' => [
    'user_status' => '1',
    'user_register_style' => 'normal',
    'user_document' => '1',
    'user_sensitive' => '1',
    'user_document_integra' => '1',
    'user_valitime' => '10',
    'user_register_second' => '10',
    'user_login_integra' => '1',
    'user_spread_integra' => '1',
    'user_search_interval' => '1',
    'user_reg_notallow' => 'www,bbs,ftp,mail,user,users,admin,administrator',
    'user_form_status' => '1',
    'user_form_check' => '0',
    'user_isLogin' => '1',
    'user_anonymous' => '0',
    'user_form_second' => '10',
    'user_replace' => '她妈|它妈|他妈|你妈|去死|贱人',
  ],
  'sitemap' => [
    'map_status' => '1',
    'map_index_freq' => 'always',
    'map_list_freq' => 'hourly',
    'map_content_freq' => 'daily',
    'map_index_priority' => '1.0',
    'map_list_priority' => '0.8',
    'map_content_priority' => '0.6',
    'map_max_limit' => '1000',
    'map_file_path' => 'sitemap',
    'map_baidu_token' => 'baidu_token',
  ],
  'rewrite' => [
    'max_page' => '100',
    'url_model' => '1',
    'compression_page' => '1',
    'url_domain' => '1',
    'category_style' => '/[listdir]/',
    'list_style' => '/[listdir]/list_page.html',
    'content_style' => '/[listdir]/[id].html',
    'search_style' => '/search-id-cid-pid.html',
  ],
  'database' => [
    'path' => 'static\\_backup',
    'part' => '20971',
    'compress' => '1',
    'level' => '9',
  ],
  'plugin' => [
    'mutex_file' => '1',
  ],
  'variable' => [
    'test' => '我是值2',
    'ceshi' => '我是测试变量的值',
  ],
  'pid' => '',
  'cid' => '',
];