<?php
return [
  'site' => [
    'site_name' => 'swiftadmin',
    'site_url' => 'www.swiftadmin.net',
    'site_logo' => '/static/images/logo.png',
    'site_http' => 'http://www.swiftadmin.net',
    'site_path' => '/',
    'site_icp' => '京ICP备13000001号',
    'site_email' => 'admin@swiftadmin.net',
    'site_keyword' => '网站关键字',
    'site_description' => '网站描述',
    'site_total' => '统计代码：',
    'site_copyright' => '版权信息：',
    'site_status' => '1',
    'site_notice' => 'html',
  ],
  'file' => '',
  'auth' => [
    'auth_code' => 'FDX8SAWA9',
    'auth_key' => 'MATwC7mt',
  ],
  'sphinx' => [
    'sphinx_status' => '0',
    'sphinx_host' => 'localhost',
    'sphinx_port' => '9213',
  ],
  'logs' => [
    'admin_log_status' => '0',
    'system_log_status' => '0',
  ],
  'cache' => [
    'cache_status' => '1',
    'cache_type' => 'redis',
    'cache_time' => '600',
    'cache_host' => '127.0.0.1',
    'cache_port' => '6379',
    'cache_user' => '',
    'cache_pass' => '',
  ],
  'upload' => [
    'upload_path' => 'upload',
    'upload_style' => 'Y-m-d',
    'upload_class' => [
      'images' => '.bmp.jpg.jpeg.png.gif',
      'video' => '.flv.swf.mkv.avi.rm.rmvb.mpeg.mpg.ogg.ogv.mov.wmv.mp4.webm.mp3.wav.mid',
      'document' => '.txt.doc.xls.ppt.docx.xlsx.pptx',
      'files' => '.exe.dll.sys.so.dmg.iso.zip.rar.7z.sql.pem',
    ],
    'upload_ftp' => '0',
    'upload_del' => '0',
    'upload_ftp_host' => '127.0.0.1',
    'upload_ftp_port' => '26655',
    'upload_ftp_user' => '123123',
    'upload_ftp_pass' => '5BGMMATwC7mtGp4m',
    'upload_http_prefix' => 'http://****.com',
    'upload_thumb' => '0',
    'upload_thumb_w' => '120',
    'upload_thumb_h' => '140',
    'upload_water' => '1',
    'upload_water_type' => '1',
    'upload_water_font' => 'swiftAdmin.net',
    'upload_water_size' => '20',
    'upload_water_color' => '#0fbeea',
    'upload_water_pct' => '49',
    'upload_water_img' => '/upload/images/2020-12-22/5fe1f8e43657e.png',
    'upload_water_pos' => '9',
  ],
  'cloud' => [
    'status' => '0',
    'type' => 'qcloud',
    'aliyun' => [
      'accessId' => '',
      'accessSecret' => '',
      'bucket' => '',
      'endpoint' => '',
      'url' => 'http://oss-cn-beijing.aliyuncs.com',
    ],
    'qcloud' => [
      'app_id' => '',
      'secret_id' => '',
      'secret_key' => '',
      'bucket' => 'testpack',
      'region' => 'ap-beijing',
      'url' => '',
    ],
  ],
  'email' => [
    'smtp_debug' => '0',
    'smtp_host' => 'smtp.163.com',
    'smtp_port' => '587',
    'smtp_name' => '管理员',
    'smtp_user' => 'yourname@163.com',
    'smtp_pass' => 'password',
    'smtp_test' => '',
  ],
  'social' => [
    'qq' => [
      'app_id' => '',
      'app_key' => '',
      'callback' => '',
    ],
    'weixin' => [
      'app_id' => '',
      'app_key' => '',
      'callback' => '',
    ],
    'weibo' => [
      'app_id' => '',
      'app_key' => '',
      'callback' => '',
    ],
  ],
  'payface' => [
    'alipay' => [
      'app_id' => '',
      'ali_public_key' => '',
      'private_key' => '',
      'return_url' => '',
      'notify_url' => '',
      'cert_client' => '',
      'cert_key' => '',
      'mode' => 'dev',
    ],
    'wechat' => [
      'app_id' => '',
      'mch_id' => '',
      'appid' => '',
      'key' => '',
      'miniapp_id' => '',
      'notify_url' => '',
      'cert_client' => '',
      'cert_key' => '',
      'mode' => '',
    ],
  ],
  'smsface' => [
    'type' => 'alisms',
    'alisms' => [
      'app_id' => 'cn-hangzhou',
      'app_sign' => '',
      'access_id' => '',
      'access_secret' => '',
    ],
    'tensms' => [
      'app_id' => '',
      'app_sign' => '',
      'secret_id' => '',
      'secret_key' => '',
    ],
  ],
  'wechat' => [
    'secret_id' => '2121',
    'secret_key' => '1212',
  ],
  'user' => [
    'user_status' => '1',
    'user_register_style' => 'normal',
    'user_document' => '1',
    'user_document_integra' => '1',
    'user_valitime' => '10',
    'user_register_second' => '10',
    'user_login_integra' => '1',
    'user_spread_integra' => '1',
    'user_search_interval' => '1',
    'user_reg_notallow' => 'www,bbs,ftp,mail,user,users,admin,administrator',
    'user_form_status' => '1',
    'user_form_check' => '0',
    'user_isLogin' => '0',
    'user_anonymous' => '0',
    'user_form_second' => '10',
    'user_replace' => '她妈|它妈|他妈|你妈|去死|贱人',
  ],
  'sitemap' => [
    'status' => '1',
    'index_freq' => 'always',
    'list_freq' => 'hourly',
    'content_freq' => 'daily',
    'index_priority' => '1.0',
    'list_priority' => '0.8',
    'content_priority' => '0.6',
    'map_xml_max' => '10000',
    'map_xml_path' => 'swiftmaps',
    'map_xml_token' => 'baidutoken',
  ],
  'rewrite' => [
    'URL_MODEL' => '1',
    'list_page' => '{listdir}/list_{page}.html',
    'content_page' => '{listdir}/{id}/',
    'list_type' => 'lists-id-{id}',
  ],
  'database' => [
    'path' => 'static\\_backup',
    'part' => '20971',
    'compress' => '1',
    'level' => '9',
  ],
  'plugin' => [
    'mutex_file' => '1',
  ],
  'variable' => [
    'test' => '我是值2',
    'ceshi' => '我是测试变量的值',
  ],
];